import Link from "next/link";
import { notFound } from "next/navigation";
import { ERE_EN } from "../data";
import SiteNav from "../../../components/SiteNav";
import ShareKit from "../../../components/ShareKit";
import { JsonLd, SITE_URL, breadcrumbSchema } from "../../../components/JsonLd";
import { englishMetadata } from "../../metadata";

export function generateStaticParams(){return Object.keys(ERE_EN).map(slug=>({slug}));}
export async function generateMetadata({params}){const { slug } = await params; const p=ERE_EN[slug];return p?englishMetadata({title:p.title,description:p.description,path:`/ere/${slug}`}):{};}
export default async function Topic({params}){const { slug } = await params; const p=ERE_EN[slug];if(!p)notFound();const url=`${SITE_URL}/en/ere/${slug}`;return <main><JsonLd data={{"@context":"https://schema.org","@graph":[{"@type":"Article",headline:p.title,description:p.description,mainEntityOfPage:url,datePublished:"2026-09-14",dateModified:"2026-09-14",author:{"@id":`${SITE_URL}/#organization`},publisher:{"@id":`${SITE_URL}/#organization`} },breadcrumbSchema([{name:"ERE Market",url:""},{name:"ERE knowledge",url:"/en/ere"},{name:p.title,url:`/en/ere/${slug}`}]) ]}}/><SiteNav locale="en"/><article className="topicPage"><section className="knowledgeHero topicHero"><div className="sectionKicker">{p.kicker}</div><h1>{p.title}<br/><em>What you need to know.</em></h1><p>{p.intro}</p><div className="answerBox"><span>SHORT ANSWER</span><strong>{p.answer}</strong></div></section><section className="section topicBody"><div className="twoCol"><div><div className="sectionKicker">PRACTICAL</div><h2>What does ERE Market<br/><em>look at?</em></h2></div><div><div className="topicList">{p.bullets.map((b,i)=><div key={b}><span>0{i+1}</span><p>{b}</p></div>)}</div><div className="sourceCards"><a href="https://www.emissieautoriteit.nl/regelgeving/hernieuwbare-energie-voor-vervoer-eres/inboeken-hernieuwbare-energie-vervoer/inboeken-elektriciteit" target="_blank" rel="noreferrer"><span>OFFICIAL SOURCE</span><strong>Netherlands Emissions Authority · electricity for transport</strong><b>View NEa source ↗</b></a></div></div></div></section><section className="section darkSection topicCTA"><div className="twoCol"><div><div className="sectionKicker">NEXT STEP</div><h2>From information<br/><em>to a real assessment.</em></h2></div><div><p>This page explains what may be possible. The ERE Check then looks at your own machines and operating hours. After that, you can submit the ERE application and mandate.</p><Link href={p.next[0]} className="button buttonPrimary">{p.next[1]} →</Link><div className="topicLinks"><Link href="/en/ere">All ERE topics →</Link><Link href="/en/ere-aanvraag">Step 2: ERE application →</Link></div></div></div></section></article><section className="section"><ShareKit locale="en" url={url} title={p.title}/></section><footer className="footer"><div className="brand"><span className="brandMark">ERE</span><span>MARKET</span></div><span>Chain control for the new energy market.</span><ShareKit locale="en" compact/></footer></main>}
