'use client';

import Link from "next/link";
import { useState } from "react";
import SiteNav from "../components/SiteNav";

export default function EreDossier(){
  const [sent,setSent]=useState(false);
  const [f,setF]=useState({company:"",email:"",phone:"",ean:"",location:"",supplier:"",route:"",secondaryEan:"",meter:"",mid:"",kwh:"",measured:"",machines:"",notes:""});
  const set=(k,v)=>setF(x=>({...x,[k]:v}));
  const message=`Hallo,\n\nDank voor het aanvullen van uw ERE-dossier bij ERE Market. Uw aanvullende gegevens zijn ontvangen en worden gekoppeld aan uw bestaande ERE-aanvraag.\n\nU hoeft nu niets meer te doen. Als wij aanvullende informatie of bewijsstukken nodig hebben, nemen wij rechtstreeks contact met u op.\n\nHartelijke groet,\nERE Market`;
  const dossier=`ERE-DOSSIER AANVULLING\n\nBedrijf: ${f.company}\nE-mail: ${f.email}\nTelefoon: ${f.phone}\nEAN: ${f.ean}\nLocatie: ${f.location}\nEnergieleverancier: ${f.supplier}\nTechnische route: ${f.route}\nSecundaire EAN / MLOEA: ${f.secondaryEan}\nType laadpunt / meter: ${f.meter}\nMID-bewijs: ${f.mid}\nVerwacht jaarvolume kWh: ${f.kwh}\nGemeten volume: ${f.measured}\nMachines / vervoer: ${f.machines}\nOpmerkingen: ${f.notes}`;
  const submit=e=>{e.preventDefault();const form=e.currentTarget;if(!form.checkValidity()){form.reportValidity();return;}form.submit();setSent(true);};
  return <main className="checkPage"><SiteNav/><div className="wrap">
    <header className="intro"><div className="eyebrow"><i/> ERE MARKET · DOSSIER</div><h1>Uw technische dossier<br/><em>aanvullen.</em></h1><p>Uw ERE-aanvraag voor 2027 is al geregeld. Hier kunt u de technische informatie aanvullen wanneer u die beschikbaar heeft.</p><small>Geen nieuwe machtiging · gegevens kunnen later worden aangevuld</small></header>
    <div className="bar"><span style={{width:"100%"}}/></div>
    {!sent ? <form className="card authorizationForm" action="https://formsubmit.co/bernardvandam@gmail.com" method="POST" target="dossierMailFrame" encType="multipart/form-data" onSubmit={submit}>
      <input type="hidden" name="_subject" value="Aanvulling ERE-dossier — ERE Market"/><input type="hidden" name="_replyto" value={f.email}/><input type="hidden" name="_autoresponse" value={message}/><input type="hidden" name="_template" value="table"/><input type="hidden" name="_url" value="https://eremarket.nl/ere-dossier"/><input type="hidden" name="Dossiergegevens" value={dossier}/>
      <section className="formSection"><div className="stepTag">01 · HERKENNING</div><h2>Bij welke aanvraag hoort dit dossier?</h2><div className="formGrid"><Field label="Bedrijfsnaam"><input name="Bedrijfsnaam" required value={f.company} onChange={e=>set("company",e.target.value)}/></Field><Field label="E-mailadres"><input name="email" type="email" required value={f.email} onChange={e=>set("email",e.target.value)}/></Field><Field label="Telefoon"><input name="Telefoon" value={f.phone} onChange={e=>set("phone",e.target.value)}/></Field><Field label="EAN · indien bekend"><input name="EAN" inputMode="numeric" value={f.ean} onChange={e=>set("ean",e.target.value.replace(/\D/g,""))}/></Field></div></section>
      <section className="formSection"><div className="stepTag">02 · AANSLUITING</div><h2>Welke aansluiting en locatie horen erbij?</h2><div className="formGrid"><Field label="Locatie elektriciteitslevering"><input name="Leveringslocatie" value={f.location} onChange={e=>set("location",e.target.value)}/></Field><Field label="Energieleverancier"><input name="Energieleverancier" value={f.supplier} onChange={e=>set("supplier",e.target.value)}/></Field><Field label="Secundaire EAN / MLOEA"><input name="Secundaire EAN MLOEA" value={f.secondaryEan} onChange={e=>set("secondaryEan",e.target.value)}/></Field><Field label="Technische route"><select name="Technische route" value={f.route} onChange={e=>set("route",e.target.value)}><option value="">Kies indien bekend</option><option>Exclusieve hoofdaansluiting</option><option>Secundair allocatiepunt / MLOEA</option><option>Geïntegreerde MID-meter in laadpunt</option><option>Weet ik nog niet</option></select></Field></div></section>
      <section className="formSection"><div className="stepTag">03 · METING EN VERBRUIK</div><h2>Wat weet u al over de meting?</h2><div className="formGrid"><Field label="Type / merk / model laadpunt of meter"><input name="Type laadpunt meter" value={f.meter} onChange={e=>set("meter",e.target.value)}/></Field><Field label="MID-bewijs / certificaatnummer"><input name="MID-bewijs" value={f.mid} onChange={e=>set("mid",e.target.value)}/></Field><Field label="Verwacht jaarvolume kWh"><input name="Verwacht jaarvolume kWh" type="number" min="0" value={f.kwh} onChange={e=>set("kwh",e.target.value)}/></Field><Field label="Gemeten volume / periode"><input name="Gemeten volume" value={f.measured} onChange={e=>set("measured",e.target.value)}/></Field></div></section>
      <section className="formSection"><div className="stepTag">04 · VERVOER EN BEWIJS</div><h2>Wat gaat u nog aanleveren?</h2><Field label="Machines / vervoer"><textarea name="Machines vervoer" rows="4" value={f.machines} onChange={e=>set("machines",e.target.value)} placeholder="Bijvoorbeeld: 20 heftrucks, 4 reachtrucks"/></Field><div className="formGrid"><Field label="Bewijs EAN / aansluiting"><input name="Bewijs EAN" type="file" accept=".pdf,.jpg,.jpeg,.png"/></Field><Field label="MID-certificaat"><input name="MID-certificaat" type="file" accept=".pdf,.jpg,.jpeg,.png"/></Field><Field label="Meetdata / laadsessies"><input name="Meetdata" type="file" accept=".pdf,.csv,.xlsx,.jpg,.jpeg,.png"/></Field><Field label="Overige documentatie"><input name="Overige documentatie" type="file" accept=".pdf,.jpg,.jpeg,.png,.doc,.docx"/></Field></div><Field label="Opmerkingen"><textarea name="Opmerkingen" rows="4" value={f.notes} onChange={e=>set("notes",e.target.value)}/></Field></section>
      <div className="bindingNotice"><strong>Dit is geen nieuwe machtiging.</strong><p>Deze pagina is uitsluitend bedoeld om uw technische ERE-dossier aan te vullen bij uw bestaande aanvraag voor 2027. Ontbrekende gegevens kunt u later nog aanleveren.</p></div>
      <button className="next full" type="submit">Dossier aanvullen en versturen <span>→</span></button><small className="formNote">U ontvangt een bevestiging op het opgegeven e-mailadres. ERE Market koppelt de gegevens aan uw dossier.</small>
    </form> : <div className="card"><div className="sentBox"><strong>✓ Uw aanvullende gegevens zijn ontvangen.</strong><p>We koppelen de informatie aan uw ERE-dossier en nemen contact op als er nog iets nodig is.</p><Link href="/" className="button buttonPrimary">Terug naar ERE Market →</Link></div></div>}
    <button className="back" onClick={()=>window.location.href="/ere-aanvraag"}>← Terug naar ERE-aanvraag</button>
  </div><iframe title="dossier verzending" name="dossierMailFrame" className="hiddenFrame"/></main>;
}
function Field({label,children}){return <label className="field"><span>{label}</span>{children}</label>}
