import Link from "next/link";
import SiteNav from "../../components/SiteNav";
import ShareKit from "../../components/ShareKit";
import { JsonLd, SITE_URL, breadcrumbSchema } from "../../components/JsonLd";
import { englishMetadata } from "../metadata";
import { ERE_EN } from "./data";

export const metadata=englishMetadata({title:"ERE knowledge base",description:"Practical guidance on EREs, electric forklifts, mobile machines, MLOEA, MID metering and ERE value.",path:"/ere"});
const groups=[["Internal electric transport",["electric-forklifts","reach-trucks","order-pickers","pallet-trucks-and-stackers","electric-tractors"]],["Technology & calculation",["mobile-electric-machines","mloea","mid-meter","ere-value-calculation"]],["Sectors",["logistics-and-distribution","construction-and-infrastructure","agriculture-and-forestry","other-electric-transport"]]];
export default function Knowledge(){return <main><JsonLd data={{"@context":"https://schema.org","@graph":[breadcrumbSchema([{name:"ERE Market",url:""},{name:"ERE knowledge",url:"/en/ere"}]),{"@type":"CollectionPage",name:"ERE knowledge base",description:"Practical guidance on EREs and electric mobility.",url:`${SITE_URL}/en/ere`}]}}/><SiteNav locale="en"/><section className="knowledgeHero"><div className="sectionKicker">ERE KNOWLEDGE BASE</div><h1>The questions behind<br/><em>ERE value.</em></h1><p>From electric forklifts to MLOEA and MID metering: clear explanations of the ERE chain, written for decision-makers and technical teams.</p><div className="sourceBadge"><span>CURRENT BASIS</span><strong>NEa · REV · electric mobility</strong></div></section><section className="section knowledgeSection"><div className="twoCol"><div><div className="sectionKicker">WHERE TO START</div><h2>Not with the price.<br/><em>With the kWh.</em></h2></div><div><p>ERE value starts with electricity that can be demonstrably delivered to transport or a mobile machine. Then come metering, evidence, booking, verification and market trading.</p><Link href="/en/ere-check" className="button buttonPrimary">Calculate your ERE potential →</Link></div></div></section>{groups.map(([group,slugs])=><section className="section knowledgeIndex" key={group}><div className="sectionKicker">{group.toUpperCase()}</div><div className="knowledgeCards">{slugs.map(slug=>{const p=ERE_EN[slug];return <Link href={`/en/ere/${slug}`} className="knowledgeCard" key={slug}><span>{p.kicker}</span><h3>{p.title}</h3><p>{p.description}</p><b>Read more →</b></Link>})}</div></section>)}<section className="section darkSection"><div className="twoCol"><div><div className="sectionKicker">OFFICIAL SOURCES</div><h2>Rules first.<br/><em>Marketing second.</em></h2></div><div><p>ERE Market uses the current NEa framework as its starting point. The knowledge base is practical guidance and does not replace a formal assessment of your connection, metering or dossier.</p><a className="button buttonPrimary" href="https://www.emissieautoriteit.nl/regelgeving/hernieuwbare-energie-voor-vervoer-eres/inboeken-hernieuwbare-energie-vervoer/inboeken-elektriciteit" target="_blank" rel="noreferrer">View NEa · electricity booking ↗</a></div></div></section><footer className="footer"><div className="brand"><span className="brandMark">ERE</span><span>MARKET</span></div><span>Chain control for the new energy market.</span><ShareKit locale="en" compact/></footer></main>}
