import Link from "next/link";
import SiteNav from "../components/SiteNav";
import ShareKit from "../components/ShareKit";
import { JsonLd, SITE_URL, breadcrumbSchema } from "../components/JsonLd";
import { englishMetadata } from "./metadata";

export const metadata = englishMetadata({ title: "Turn electric energy into market value", description: "ERE Market takes the ERE chain off your hands — from technical assessment and measurement to registration, booking and sale.", path: "" });

const sectors = [
  ["Logistics & distribution", "Forklifts, reach trucks, order pickers, pallet trucks and other internal electric transport.", "/en/ere/logistics-and-distribution"],
  ["Construction & infrastructure", "Electric excavators, mobile cranes, bulldozers and other mobile equipment.", "/en/ere/construction-and-infrastructure"],
  ["Agriculture & forestry", "Electric tractors, agricultural vehicles, forestry machines and mobile equipment.", "/en/ere/agriculture-and-forestry"],
  ["Other electric transport", "An electric truck, other road vehicle or qualifying charging point can be assessed in the same chain.", "/en/ere/other-electric-transport"],
];
const steps = [["01","Check","See in two minutes whether your electric fleet is worth assessing."],["02","Control","We check the connection, metering and required evidence."],["03","Book","Eligible electricity is registered and booked in the REV."],["04","Trade","We bring the resulting EREs to the market."],["05","Pay out","You receive the value created by the eligible volume."]];

export default function EnglishHome(){return <main>
  <JsonLd data={{"@context":"https://schema.org","@graph":[breadcrumbSchema([{name:"ERE Market",url:""}]),{"@type":"WebSite",name:"ERE Market",url:`${SITE_URL}/en`,description:"EREs from electric mobility: assessment, booking and market trading."}]}}/>
  <SiteNav locale="en"/>
  <section className="hero"><div className="heroGrid"/><div className="heroContent"><div className="eyebrow"><span/> FOCUS ON INTERNAL ELECTRIC TRANSPORT · LOGISTICS · DC · WAREHOUSING</div><h1>Turn your electric energy into <em>market value.</em></h1><p className="heroLead">Your forklifts, reach trucks and other internal electric vehicles already consume significant amounts of electricity. Under the applicable conditions, that electricity can create EREs. ERE Market takes the chain off your hands — from assessment and measurement to registration, booking and sale. Internal electric transport is our core; other qualifying electric transport on the same site can be assessed in the same chain.</p><div className="heroActions"><Link href="/en/ere-check" className="button buttonPrimary">Calculate your ERE potential <span>→</span></Link><Link href="/en/hoe-het-werkt" className="textLink">See how it works</Link><Link href="/en/ere-aanvraag" className="textLink">Already completed the first scan? Start step 2 →</Link></div><div className="heroMeta"><span>Free</span><i/><span>No obligation</span><i/><span>2 minutes</span></div></div><div className="heroPanel"><div className="panelTop"><span>EXAMPLE VALUE</span><span className="live"><b/> CALCULATION EXAMPLE</span></div><div className="panelNumber">€<strong>153,000</strong></div><div className="panelLine"><span>1,000,000 kWh</span><span>≈ 333,000 EREs</span></div><div className="valueBar"><span/></div><div className="panelLine"><span>ERE price</span><span>€0.46 / ERE</span></div><p>Example based on 0.3327 ERE/kWh and €0.46 per ERE. Actual eligible volume and proceeds depend on the electricity that can be booked and the market price.</p></div></section>
  <section className="proofStrip"><div><strong>ELECTRIC MACHINES</strong><span>The source of measurable ERE value</span></div><div><strong>REGISTRATION</strong><span>Metering & evidence</span></div><div><strong>MARKET</strong><span>Aggregation & trading</span></div><div><strong>DATA</strong><span>Insight per site</span></div></section>
  <section className="section intro"><div className="sectionKicker">VALUE ALREADY ON YOUR SITE</div><div className="twoCol"><h2>What is an ERE?<br/><em>And why does it have value?</em></h2><div><p>ERE stands for Emission Reduction Unit. One ERE represents one kilogram of CO₂-equivalent lifecycle emission reduction compared with the fossil reference. The system creates a market value for eligible emission reductions in transport.</p><p>The Dutch Emissions Authority (NEa) runs the system and the Register Energy for Transport (REV). Companies with eligible electric transport can, under the applicable conditions, have electricity booked and receive EREs. ERE Market organises the chain.</p><Link href="/en/ere-check" className="arrowLink">See what your site could generate →</Link></div></div><div className="simpleFlow">{steps.map(([n,t,x])=><div key={n}><b>{n.replace('0','')}</b><span>{x}</span></div>)}</div><div className="momentum"><strong>The market is live.</strong><span>The ERE system has applied since 1 January 2026. The REV is the NEa register in which eligible deliveries are booked and EREs are recorded.</span></div></section>
  <section className="section darkSection"><div className="sectionKicker">WHO WE SERVE</div><div className="sectionHead"><h2>From warehouse floor<br/><em>to electric transport.</em></h2><p>Our core is internal electric transport: forklifts, reach trucks, order pickers, pallet trucks, stackers, electric tractors and other mobile equipment. If an electric truck, road vehicle or qualifying charging point is also present, we can assess it as part of the same chain.</p></div><div className="sectorGrid">{sectors.map(([t,x,h],i)=><Link href={h} className="sectorCard" key={t}><span className="cardNumber">0{i+1}</span><h3>{t}</h3><p>{x}</p><span className="cardArrow">→</span></Link>)}</div></section>
  <section className="section process"><div className="sectionKicker">FROM ELECTRICITY TO ERE</div><div className="sectionHead"><h2>From production<br/><em>to sale.</em></h2><p>ERE Market coordinates the chain from technical qualification to market sale.</p></div><div className="steps">{steps.map(([n,t,x])=><div className="step" key={n}><span>{n}</span><h3>{t}</h3><p>{x}</p></div>)}</div></section>
  <section className="section knowledgeTeaser"><div><div className="sectionKicker">KNOWLEDGE</div><h2>The questions behind<br/><em>ERE value.</em></h2><p>From electric forklifts to MLOEA, MID metering and ERE yield: clear explanations based on the current NEa framework.</p></div><div className="knowledgeTeaserLinks"><Link href="/en/ere/electric-forklifts">Electric forklifts →</Link><Link href="/en/ere/reach-trucks">Reach trucks →</Link><Link href="/en/ere/mloea">MLOEA →</Link><Link href="/en/ere/ere-value-calculation">Calculate ERE value →</Link><Link href="/en/ere">View the full knowledge base →</Link></div></section>
  <section className="section acquisition"><div className="acqBox"><div><div className="sectionKicker">START HERE</div><h2>Start with your<br/><em>ERE potential.</em></h2><p>No EAN or documents needed. In two minutes you can see whether your site is worth a deeper assessment.</p></div><div className="heroActions"><Link href="/en/ere-check" className="button buttonPrimary">Run the free ERE Check →</Link><Link href="/en/ere-aanvraag" className="textLink">Go to step 2: ERE application →</Link></div></div></section>
  <section className="section"><ShareKit locale="en" url="https://eremarket.nl/en/ere-check" title="ERE Market — electric fleet ERE check"/><p className="marketDisclaimer">ERE Market is not a central exchange. The Dutch ERE market is new and market data is still developing. NEa does not set the trading price.</p></section>
  <footer className="footer"><div className="brand"><span className="brandMark">ERE</span><span>MARKET</span></div><span>Chain control for the new energy market.</span><ShareKit locale="en" compact/><div className="footerLinks"><Link href="/en/ere">ERE knowledge →</Link><Link href="/en/hoe-het-werkt">How it works →</Link><Link href="/en/ere-aanvraag">Step 2: ERE application →</Link></div></footer>
</main>}
